### ISSUE TITLE
Missing space during parsing, causing invalid input

### ISSUE THREAD

**Issue by PPBouquet** [snipsco/snips-nlu-metrics#104]
Hi, I've encountered a problem when using both **snips-nlu** + **snips-nlu-metrics**.
Simple case scenario:
I have a folder containing 2 (custom) entities and one intent as follow:
**entity_ent1**:
    `foo`
**entity_ent2**:
    `bar`
**intent_int1**:
    `Show me [ent1:ent1](foo) [ent2:ent2](bar)`

I then use the `AssistantDataset` from **snips_nlu.cli.dataset.assistant_dataset** to generate the json dataset.
One part might look like the following:
```{'data': [{'text': 'Show me '}, {'entity': 'ent1', 'text': 'foo', 'slot_name': 'ent1'}, {'entity': 'ent2', 'text': 'bar', 'slot_name': 'ent2'}]}```

So far so good.
Now using `compute_cross_val_metrics` from **snips-nlu-metrics**, the following json has this part:
```
"parsing_errors": [
    {
      "expected_output": {
        "input": "Show me foobar",
        ......
```
The space is missing between foo and bar, causing of course a mistake during slot recognition.

**Comment by adrienball** [comment]
Hi @PPBouquet ,
In your example there is no space between foo and bar, because you did not explicitly declare it.
Here is how your data should look like:
```json
{
  "data": [
    {
      "text": "Show me "
    },
    {
      "entity": "ent1",
      "text": "foo",
      "slot_name": "ent1"
    },
    {
      "text": " "
    },
    {
      "entity": "ent2",
      "text": "bar",
      "slot_name": "ent2"
    }
  ]
}
```

Whitespaces are not used in all languages to separate words or tokens so, in order to be language agnostic, no characters are added implicitly.
Cheers

**Comment by PPBouquet** [comment]
Thanks for that answer @adrienball .
However, the json provided was generated by the **AssistantDataset** in **snips-nlu** (version 0.17.0) and I guess I have no control over it. Which means I have to overwrite the json dataset for every whitespace ?

**Comment by adrienball** [comment]
My bad, I read too quickly, there seems to be indeed a bug when loading the dataset from the text files format. I will add an issue on the **snips-nlu** repo and try to fix it ASAP.
Thanks a lot for reporting.

**Comment by adrienball** [comment]
Closing this issue, as it should be fixed now.
